service: imux
plugins:
  - serverless-finch
  - serverless-wsgi
custom:
  client:
    bucketName: ${env:WEBSITE_BUCKET, '${self:service}-${self:provider.stage}-website'}
    objectHeaders:
      ALL_OBJECTS:
        - name: Content-Type
          value: text/html
  domain: ${env:DOMAIN, 'imux.email'}
  emails: ${env:EMAILS_BUCKET, '${self:service}-${self:provider.stage}-emails'}
  kms: !Join ['', ['arn:aws:kms:${self:provider.region}:', !Ref AWS::AccountId, ':alias/aws/ses']]
  owner: ${env:OWNER_EMAIL}
  wsgi:
    app: imux.web_api.app
provider:
  name: aws
  runtime: python3.8
  environment:
    ACCOUNTS: !Ref accounts
    DECRYPT: ${self:service}-${self:provider.stage}-decrypt
    DOMAIN: ${self:custom.domain}
    INTRO: !Ref intro
    KMS: ${self:custom.kms}
    ORDERS: !Ref orders
    RECEIVE: !Ref receive
    RULESET: !Ref ruleset
    STRIPE_KEY: ${env:STRIPE_PRIVATE_KEY}
    STRIPE_WEBHOOK: ${env:STRIPE_WEBHOOK}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: !GetAtt accounts.Arn
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: !Join ['', ['arn:aws:lambda:${self:provider.region}:', !Ref AWS::AccountId, ':function:${self:service}-${self:provider.stage}-decrypt']]
    - Effect: Allow
      Action: s3:GetObject
      Resource: arn:aws:s3:::${self:custom.emails}/*
    - Effect: Allow
      Action: s3:ListBucket
      Resource: arn:aws:s3:::${self:custom.emails}
    - Effect: Allow
      Action: kms:Decrypt
      Resource: '*'
    - Effect: Allow
      Action: ses:SendBulkTemplatedEmail
      Resource: !Join ['', ['arn:aws:ses:${self:provider.region}:', !Ref AWS::AccountId, ':identity/${self:custom.domain}']]
functions:
  api:
    handler: wsgi_handler.handler
    cors: true
    events:
      - http: ANY /
      - http: ANY /{any+}
  decrypt:
    runtime: ruby2.5
    handler: decrypt.handler
  forward:
    handler: imux.email_handler.forward
    events:
      - s3:
          bucket: ${self:custom.emails}
          event: s3:ObjectCreated:*
          existing: true
  accounts:
    handler: imux.account_manager.handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt accounts.StreamArn
resources:
  Resources:
    policy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.emails}
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource: arn:aws:s3:::${self:custom.emails}/*
              Sid: ${self:service}-${self:provider.stage}-AllowSESPuts
              Principal:
                Service: ses.amazonaws.com
              Condition:
                StringEquals:
                  aws:Referer: !Ref AWS::AccountId
    ruleset:
      Type: AWS::SES::ReceiptRuleSet
      Properties:
        RuleSetName: ${self:service}-${self:provider.stage}-ruleset
    help:
      Type: AWS::SES::ReceiptRule
      Properties:
        RuleSetName: !Ref ruleset
        Rule:
          Enabled: true
          Recipients:
            - help@imux.email
          Actions:
            - AddHeaderAction:
                HeaderName: To
                HeaderValue: ${self:custom.owner}
            - StopAction:
                Scope: RuleSet
    receive:
      Type: AWS::SES::ReceiptRule
      Properties:
        RuleSetName: !Ref ruleset
        After: !Ref help
        Rule:
          Enabled: true
          Recipients:
            - dummy@imux.email
          Actions:
            - S3Action:
                BucketName: ${self:custom.emails}
                KmsKeyArn: ${self:custom.kms}
    intro:
      Type: AWS::SES::Template
      Properties:
        Template:
          SubjectPart: Subscription Notification
          HtmlPart: |
            <p>
            Hello,
            </p>
            <p>
            You have been added as a recipient of shared emails via
            <a target="_blank" rel="noopener noreferrer" href="https://${self:custom.domain}">${self:custom.domain}</a>.
            <br>
            To ensure that you receive messages as reliably as possible,
            please add <b>{{uuid}}@${self:custom.domain}</b> to your address book.
            <br>
            If you believe that you should not have received this notification, click
            <a target="_blank" rel="noopener noreferrer" href="https://${self:custom.domain}/unsubscribe/{{uuid}}/{{unsubscribe}}">here</a>
            to unsubscribe.
            </p>
            <p>
            This is an automated message, please do not reply.
            </p>
    accounts:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
    orders:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
